Sprint 05
mahlenko/MovieQuiz-ios pull request #4
Opened 2022-09-08 22:09 UTC by mahlenko

2022-09-10 07:44 UTC, ABashkirova requested changes

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Models/AnsweredStore.swift
> +    var failed: [QuizQuestion] = []
У вас mutable доступ до свойств структуры. Судя по всему вы изменяете эти элементы в  store. Поэтому возможно стоит добавить модификатор доступа только на get : `private(set)`

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Models/Quiz/QuizModel.swift
> +            } catch {}
Необработанная ошибка ведет к логическому тупику. Приложение "зависает" и дальше пройти не возможно. Попробуйте выключить интернет и пройти квиз.

Стоит обрабатывать ошибки и в случае провала – возвращать управление UI, чтобы пользовать мог повторить загрузить данные.

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Models/Quiz/QuizModel.swift
> +    }
В этих функциях можно return опускать, но это дело вкуса.

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Services/Question/QuestionFactoryProtocol.swift
> +    init (delegate: QuestionFactoryDelegate)
Какая потребность в инициализаторе в протоколе?

Протокол нужен чтобы описать методы и свойства взаимодействия с элементом – контракт. Так, чтобы скрыть конкретную реализацию класса. Добавлять инициализатор – значит добавлять ограничение на реализацию, которая должна иметь конкретную зависимость  - QuestionFactoryDelegate. То есть вы заранее говорите о формате отношений на выходе. Вам нужно обойтись более гибким вариантом – только функция requestNextQuestion. Реализация может зависеть от QuestionFactoryDelegate, а может нет. Вам как пользователю сервиса с реализацией QuestionFactoryProtocol должно быть не важно за внутреннюю реализацию.

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Services/Question/QuestionIMDBFactory.swift
> +        NetworkImDBClient(apiKey: apiKey)
Два замечания:
1) пересоздаете элемент каждый раз обращаясь за фильмами. Не очень экономный подход. 
2) Вам рассказывали про инджекцию. Хорошо бы передавать клиент в инициализатор. 

К исправлению не обязательно, можно оставить до следующего модуля. Там такой код не будет принят на ревью.

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Services/Question/QuestionIMDBFactory.swift
> +                DispatchQueue.main.async {
Это удобно обернуть все на главную очередь. Тогда не придется заботиться о каждом возврате значений на UI.

Однако лучше такое делать ближе к месту возвращения на UI. 
Так вы избежите запуска сложных операций на главном потоке, и потенциальные фризы вам не будут страшны.

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Services/Question/QuestionIMDBFactory.swift
> +                            })
```suggestion
                            responseData?.forEach { movieData in
                                let rating = Float(movieData.imDbRating) ?? 0.0

                                self.data.append(
                                    QuizQuestion(
                                        image: movieData.image,
                                        rating: rating,
                                        text: "Рейтинг \"\(movieData.title)\" больше, чем 7?",
                                        correctAnswer: rating > 7.0
                                    )
                                )
                            }
```

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Services/ResultAlertPresenter.swift
> +    }
В отрыве от задания, выглядит очень странно причем тут ResultAlertPresenter и QuestionFactoryDelegate, не думаете? какой-то презентер результата и какая-то фабрика вопросов. Нужны они друг другу?

Еще более странным выглядит в итоге `self.delegate as? UIViewController`. 

Зачем себе усложнять жизнь: передавая нечто по протоколу, при этом не использовав ни один из методов протокола? 

Если у вас получается написать код, который сложно использовать, пробуйте вернуться назад к началу и задать вопрос: а все ли я правильно делаю и как обойтись иначе? 
Архитектурные паттерны сложны, не с первого раза могут поддаться, это нормально. Давайте Вернем как советуют в уроке - UIViewController

+ сделайте сохранение по слабой ссылке, так вы избежите ссылочного цикла.

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Services/Question/QuestionIMDBFactory.swift
> +                            }
Все верно сделали!

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Services/Question/QuestionIMDBFactory.swift
> +                            }
Единственное, здесь лучше подходит guard

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Services/Question/QuestionIMDBFactory.swift
> +                            })
```suggestion
                            let responseData = json.items.filter { item in
                                return !item.imDbRating.isEmpty
                            }
```

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Services/Question/QuestionIMDBFactory.swift
> +        NetworkImDBClient(apiKey: apiKey)
И еще одно. Достаточно расточительно ходить за новыми вопросами на каждую игру, если вам сервис возвращает гораздо больше фильмов. Лучше сохранить их, и чанковать в другом месте.

2022-09-10 07:44 UTC, ABashkirova commented on MovieQuiz/Services/Question/QuestionIMDBFactory.swift
> +    public let delegate: QuestionFactoryDelegate
давайте здесь добавим слабую ссылку, потому что так вы создаете сильный ссылочный цикл 

К сожалению, в модуле спринта про это не рассказали и пока не успели добавить новый материал.

2022-09-11 09:11 UTC, ABashkirova reviewed
Можно убрать каст, чтобы повысить свойства тестируемости кода.

2022-09-11 09:11 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questions.load()
```suggestion
        let questionsFactory = QuestionNetworkFactory(client: NetworkClient(), delegate: self)
        questionsFactory.load()
        questions = questionsFactory
```

2022-09-11 14:15 UTC, mahlenko commented on MovieQuiz/Services/Question/QuestionIMDBFactory.swift
> +    public let delegate: QuestionFactoryDelegate
При добавлении слабой ссылки, получаю ошибки. Не понимаю как это правильно сделать.

`weak var delegate: QuestionFactoryDelegate?`

'weak' must not be applied to non-class-bound 'any QuestionFactoryDelegate'; consider adding a protocol conformance that has a class bound

2022-10-07 22:23 UTC, mahlenko commented
Finish

2022-10-11 09:55 UTC, merged